add-time-limit
roenschg/php-newrelic pull request #10
Opened 2019-01-28 12:41 UTC by TTezcan

2019-01-28 18:29 UTC, roenschg requested changes
Please fix the following points first:
- See the comments at the code
- Check with vendor/bin/phpcs for the code style
- Please also create a PR for the 7.x version as well with your changes.

2019-01-28 18:29 UTC, roenschg commented on src/Groensch/NewRelic/CustomEventHandler/AutoBulkHttp.php
> +        $this->startTimer();
Please format like this:

```
$this
    ->setNewRelicHttpApi($httpApi)
    ->startTime()
;
```

2019-01-28 18:29 UTC, roenschg commented on tests/Groensch/NewRelic/CustomEventHandler/AutoBulkHttpTest.php
> +        sleep(1);
Sleep slows down the tests. I would recommend to test the actual isTimeOver() method first and the mock it in every test by returning the true or false.

2019-01-28 18:29 UTC, roenschg commented on src/Groensch/NewRelic/CustomEventHandler/AutoBulkHttp.php
> +    protected $timeToPassInSec = 30;
Please consider to make this as a configurable optional parameter in the constructor.

2019-01-28 18:29 UTC, roenschg commented on src/Groensch/NewRelic/CustomEventHandler/AutoBulkHttp.php
> +    protected $lastTimeInEpoch;
Please consider a different naming like: lastTimeBufferWasFlushed()

2019-01-29 16:00 UTC, roenschg requested changes

2019-01-29 16:00 UTC, roenschg commented on src/Groensch/NewRelic/InvalidArgumentException.php
> +class INVALIDARGUMENTEventException extends \Exception
What happened here to the name of the class? And where is it used?

2019-01-30 17:40 UTC, roenschg approved these changes

2019-01-30 17:41 UTC, merged

2019-09-25 14:21 UTC, andreas-weber commented
:D :D :D :D